name: Python CI and Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
  - name: Copy the code to test
    uses: actions/checkout@v2
  - name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: '3.12'
  - name: Install dependancies 
    run: python -m pip install --update pip && pip install pytest
  - name: Test code with pytest
    run: pytest

      